version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10.16
    working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - run: cd workspace
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - persist_to_workspace:
          root: workspace
          paths:
            - node_modules
            - build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn test:ci
  coverage:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn coverage:ci
  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: lint

workflows:
  everything:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
