version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn
      - run: yarn test:ci
  coverage:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn
      - run: yarn generate-ts
      - run: yarn coverage:ci
  lint:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn
      - run: yarn lint

workflows:
  build_and_test:
    jobs:
      - test
      - coverage
      - lint
