version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn test:ci
  coverage:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn coverage:ci

workflows:
  build_and_test:
    jobs:
      - test
      - coverage
